### ISSUE TITLE
How many vaults are supported?

### ISSUE THREAD

**Issue by wenlzhang** [hauselin/obsidian-alfred#11]
Previously I had five vaults in total, and everything worked fine. Today, I created a sixth vault and added it to path by using `oaddvault my sixth vault`. However, `oo my sixth vault` cannot locate this vault, and only the five previously created vaults are listed. Also, I observe the following:

- If I try to open the sixth vault with `ov my sixth vault` while Obsidian is open, it would give the hint "Available vaults: obsidian help". However, "my sixth vault" can be opened correctly.
- If I try to open the sixth vault with `ov my sixth vault` while Obsidian is closed, one of the previously opened vaults rather than "my sixth vault" would be opened.

I also tried to create the seventh vault, and there are the same issues.

**Comment by hauselin** [comment]
It should definitely support more than 6 vaults (100 is maximum, but that number can be changed easily but I can't imagine someone having so many vaults). It worked when I tested it just now.

The problems with the wrong vault being opened could be Electron-related issues (see README for known bugs), which means there's not much I can do about it. Unless I'm misunderstanding your problem. 

Try manually clearing your workflow variables to remove the problematic vaults. See if that helps. See gif below to see how to do it.

Finally, try a clean install of the workflow to see if that solves your problems. You should have to add all your vaults one by one again. 

If the problems persist, I'll need more details before I can help.

![CleanShot 2020-12-17 at 18 43 13](https://user-images.githubusercontent.com/7620977/102557036-444c7480-4098-11eb-9224-ad171dce4639.gif)

**Comment by wenlzhang** [comment]
It is very strange that `oaddvault my sixth vault` did not add the sixth vault to the environment variables. However, a clean installation of the workflow resolves the issue. Now I can add more vaults.

**Comment by hauselin** [comment]
Glad it's fixed!
