### ISSUE TITLE
Additional date formats?

### ISSUE THREAD

**Issue by tward09** [hauselin/obsidian-alfred#13]
I use a MMMM D, YYYY format for my daily notes "December 23, 2020" for example. Is there a way I can change the date format for the daily note to reflect that format?

**Comment by hauselin** [comment]
I've updated the workflow but haven't released it yet. You can try it out by downloading from it [here (right click and save link)](https://github.com/hauselin/obsidian-alfred/raw/month-format/Obsidian.alfredworkflow) (from another branch). Let me know if it works for you. 

Run `odailyformat` and enter `MMMM D, YYYY` first.

**Comment by tward09** [comment]
Works perfectly. Thanks!
