### ISSUE TITLE
When the dailypath directory is specified, can the parsing of `~` symbols be supported?

### ISSUE THREAD

**Issue by iT-Boyer** [hauselin/obsidian-alfred#17]

**Comment by hauselin** [comment]
Yes, `~` should be parsed/encoded properly. But if for some reason you're doing something different, try manually specifying the path. Open the workflow environment variables panel by clicking the icon that looks like [x]. Then modify the value associated with `dailyabspath`.

**Comment by iT-Boyer** [comment]
the `~` cannot be parsed correctly at this time.
1. dailyabspath : ~/Journal
2. print this log when use`on` to create new journal
```
~/Journal
~/Journal/jj.md
Note doesn't exist. Creating note.
```

**Comment by hauselin** [comment]
Is there any reason why you're using ~ instead of the path to your home directory (e.g., /users/john/Journal), since ~ is just a shortcut to your home directory?

**Comment by iT-Boyer** [comment]
I use a similar `mackup` tool to manage data between multiple computers. Because of different user names, I will solve this problem through `~` symbols. Therefore, I suggest whether this workflow can support this `~`symbol.

**Comment by hauselin** [comment]
Okay. It's probably doable via `app.pathTo("home folder")`. I'll try to implement it in the next few days. Though it'll mean you'll have to manually specify all your paths in the workflow (instead of using `odailypath` etc.).

**Comment by hauselin** [comment]
I've updated the workflow. Download it [here](https://www.dropbox.com/s/o3d5hbbvr7aftcy/Obsidian.alfredworkflow?dl=1). Let me know if it works for you, @iT-Boyer. You'll have to open the environment variable panes (click [ x ] at the top right of the workflow) to manually modify all the relevant paths (e.g., `/Users/John/Obsidian/notes` to `~/Obsidian/notes`).

**Comment by iT-Boyer** [comment]
I updated version 0.2.5, but still can't parse `~` symbols

**Comment by hauselin** [comment]
That's odd. If you don't mind, could you take a screenshot of your workflow environment variables? Something like that: 

![image](https://user-images.githubusercontent.com/7620977/106967348-032a2580-6715-11eb-8333-d474d4498677.png)

And it'd be helpful if you could take a screenshot of the debugging pane/output in Alfred after you run `od`. That is, open the debugging pane first, then run `od`.

![image](https://user-images.githubusercontent.com/7620977/106967675-93686a80-6715-11eb-9be9-433b8c5c2973.png)

**Comment by iT-Boyer** [comment]
I updated version 0.2.6, but still can't parse ~ symbols.
YES，The screenshot below is my configuration and log information：
![截屏2021-02-22 下午1 35 44](https://user-images.githubusercontent.com/4022953/108666913-35a89080-7513-11eb-9655-e5aa09d902b6.png)
![截屏2021-02-22 下午1 37 13](https://user-images.githubusercontent.com/4022953/108666920-393c1780-7513-11eb-930f-dd071dbeafb5.png)

**Comment by iT-Boyer** [comment]
Through troubleshooting, only this `on` command has problems. 

Change the `vpath` to this:
```js
var homepath = app.pathTo('home folder')
vpath = vpath.replace('~', homepath)

var filepath = vpath + "/" + fname + ".md";
console.log("filepath: " + filepath)
```

**Comment by lastobelus** [comment]
Unfortunately, globally replacing `~` with home directory breaks everything for vaults that live in an ICloud Drive folder, because ICloud uses `~` in names instead of `.`, ex:

       /Users/lasto/Library/Mobile\ Documents/com~apple~CloudDocs/ObsidianNotes/Obsidian--Alfred\ Workflow.md
