### ISSUE TITLE
Failure to search vault

### ISSUE THREAD

**Issue by ryanjamurphy** [hauselin/obsidian-alfred#18]
First, thanks for this—beautiful workflow, and I am excited to get it fully operational.

Second: this issue is probably me being an edge case. A solution might be hard to grasp.

The problem: I only have on vault, but this workflow fails to search it. Instead, I get markdown files from across my Mac—even when I'm using `oss` or `orr`. 

Curiously, the workflow has no issue accessing daily notes (e.g., `otmr` works fine.) 

My vault is located in `/Users/ryanjamurphy/Library/Containers/co.noteplan.NotePlan3/Data/Library/Application Support/co.noteplan.NotePlan3`, as I use NotePlan 3 to access the same files. My guess is that since this location is a sandbox (I think?), Alfred/the workflow doesn't like searching it.

Any ideas welcome!

**Comment by hauselin** [comment]
Hmm. That's odd. Have you tried the solutions described [here](https://github.com/hauselin/obsidian-alfred/issues/15#issuecomment-753414360)? Let me know if they fix your problem. If not, we'll look more into it...

**Comment by ryanjamurphy** [comment]
So sorry, I should've checked there first. Step #2 was the problem. Indeed, it was treating the sandboxed files as system files.

Thanks again! Brilliant work!
