### ISSUE TITLE
Add to daily note from Alfred?

### ISSUE THREAD

**Issue by ghost** [hauselin/obsidian-alfred#19]
Not familiar with Obsidian or Alfred APIs, but would it be possible to add text to daily note (or some unprocessed notes file) from Alfred? That way I could record some thoughts, without ever having to break my focus(context switching to Obsidian)

 If this is possible, I could probably implement with a few code pointers.

**Comment by hauselin** [comment]
Yes, it's definitely possible. I actually have this feature in my own development version but haven't used it much myself. The difficulty with trying to implement such a feature is different people will have different use cases: add/append text to a particular section or to the end as a new paragraph or a new bullet point/list item, so I don't know what's the best way to implement it. If you thoughts/suggestions, let me know. Thanks1

**Comment by ghost** [comment]
@hauselin Good news! 

I think the simplest approach would be a generic inbox file. Every time you send text, it would just append a new bullet point to the file. Then later, when ready to process all the random text snippets, one could go to that file and process into their second brain. 

Alfred cmd would look like ```on This is the text i'd like to append to my inbox file #notes #focus [[efficiency features]]```

Any more fancy than that, I think we run into the problem you're describing, trying to guess structure of unstructured notes.

**Comment by hauselin** [comment]
Try this [updated version](https://www.dropbox.com/s/dt8tawyc5wv09yq/Obsidian_dev.alfredworkflow?dl=1). Make sure to back up your vault/notes first!

Use `oinbox` to specify the markdown file you want to use as the inbox. Then you can use `oi some text to append` to append to that note. Let me know how it works.

**Comment by ghost** [comment]
Very nice. It doesn't like apostrophe's ```'``` or new lines (pasted in) 
```
Suspendisse potenti. Nam convallis ante et justo aliquet dignissim. Aenean scelerisque tempor nunc sit amet tincidunt. Suspendisse rutrum malesuada eros, vitae elementum nunc sagittis lacinia. Mauris tempus quam vel risus fermentum, ut luctus erat malesuada. Nunc ut sem scelerisque, tristique urna ac, scelerisque neque. In dignissim tincidunt enim et pulvinar. Nulla semper dolor in commodo sollicitudin.

Sed consectetur pulvinar diam, eu aliquam arcu gravida ac. Aliquam placerat convallis quam, eget posuere purus mattis non. Donec pellentesque est velit, at hendrerit sapien tristique sit amet. Proin sodales nulla quis dolor suscipit facilisis. Aliquam commodo efficitur ultrices. Praesent vel consectetur lectus. Nullam imperdiet erat at magna bibendum, quis finibus ligula vulputate. Nulla semper, tortor nec gravida sagittis, lectus nisl fermentum purus, in sodales diam est in elit.
```

All the other symbols seem to work great, and you can put some really really long strings in too!

**Comment by hauselin** [comment]
See if [this version](https://www.dropbox.com/s/83kypll4aki5bxr/Obsidian_dev2.alfredworkflow?dl=1) fixes those two problems?

**Comment by ghost** [comment]
Apostrophe works now. New line creates new bullet point, which I guess is expected given bulletpoints in list. 

Works great the state that its in, thanks for enabling these quick notes!

**Comment by hauselin** [comment]
I've updated the documentation and workflow in the repo. Also, it's possible to use a hotkey to directly append clipboard contents into your note.
