### ISSUE TITLE
Accented characters and copy link function

### ISSUE THREAD

**Issue by ldebritto** [hauselin/obsidian-alfred#2]
Hi @hauselin , thanks for that workflow!

I've found out that you workflow is not suited to deal with accented characters in file name (like ã, é, ï, ô, ú)

Also, I would like to suggest the addition of a "Copy link to file" option. I've added that myself to the bash scripts and uploaded to a Fork!

Sorry if I messed up something, I'm both new to programming as well as to GitHub itself!

**Comment by hauselin** [comment]
Hi @ldebritto, if you make a pull request, I can merge your changes into my repo.

**Comment by hauselin** [comment]
FYI, @ldebritto, the workflow now works with special characters.
