### ISSUE TITLE
oi command cannot recognize Chinese characters correctly

### ISSUE THREAD

**Issue by wenlzhang** [hauselin/obsidian-alfred#21]
The `oi` command can add English characters to the inbox note correctly. However, all Chinese characters in a sentence would be replaced as "?".

Also, would it be possible to give some kind of notification saying that the sentence is added to the selected Obsidian note or something?

**Comment by hauselin** [comment]
Let me try to fix them in the next few days. I'll let you know when I have an updated version for you to test.

**Comment by ghost** [comment]
If notification is added, can it be made optional?

**Comment by wenlzhang** [comment]
There may be some other symbols that cannot be recognized by the `oi` command.

For instance, when copying the current issue page as a Markdown link, the correct text should be:
[oi command cannot recognize Chinese characters correctly · Issue #21 · hauselin/obsidian-alfred](https://github.com/hauselin/obsidian-alfred/issues/21)

When adding the text above through `oi`, however, it would be become:
[oi command cannot recognize Chinese characters correctly � Issue #21 � hauselin/obsidian-alfred](https://github.com/hauselin/obsidian-alfred/issues/21)

**Comment by hauselin** [comment]
Thanks! I'm testing a solution that should address these problems. I'll probably provide an update within the next few days!

**Comment by hauselin** [comment]
Hey @wenlzhang and @LouisInFlow, here's an [updated version](https://www.dropbox.com/s/83xqcubhbjhgmtn/Obsidian_dev.alfredworkflow?dl=1). Remember to back up your notes/vault. It should now support special characters. Notifications are turned on by default. But if you want to disable it, run `oinotify` to toggle on/off. Let me know if you run into more issues.

**Comment by ghost** [comment]
我用`https://ctext.org/dao-de-jing`式。没有什么问题。谢谢

**Comment by hauselin** [comment]
> 我用`https://ctext.org/dao-de-jing`式。没有什么问题。谢谢

Took me a while to parse that! Haven't read complete Chinese sentences for quite a while :p Thanks for testing! I'll release this version later today.
