### ISSUE TITLE
An error occurred when obsidian://open and obsidian://search

### ISSUE THREAD

**Issue by iT-Boyer** [hauselin/obsidian-alfred#22]
![截屏2021-02-22 下午2 52 29](https://user-images.githubusercontent.com/4022953/108672894-bcfb0180-751d-11eb-9c9f-b8b70ff78e1a.png)

**Comment by hauselin** [comment]
Which command did you run? Is it `on`?

Edit: Ok, I just saw your [reply](https://github.com/hauselin/obsidian-alfred/issues/17#issuecomment-783464040) and modification in #17 and you've closed the issue, so it looks like you've found the solution? I'll implement that change later and will test it too. Let me know if you're still running into issues though.

**Comment by iT-Boyer** [comment]
There is still a problem with the open mode of the on command, which is fixed by the following code. I hope there is a better solution.
```js
//uri = "obsidian://open?vault=" + encodeURIComponent(v) + "&file=" + encodeURIComponent(fname);
//after
uri = "obsidian://open?path=" + encodeURIComponent(filepath);
```

**Comment by hauselin** [comment]
Ok. Thanks for letting me know! I'll take a look later this week. Glad it's at least functional for you now.

**Comment by iT-Boyer** [comment]
This `Alfred fallback search` workflow has the same problem：
```sh
obsidian://search?vault=%E7%9F%A5%E4%B9%8E%E5%B9%B4&query=hahhh
```

**Comment by hauselin** [comment]
Is it a problem with Chinese/special characters again?

I can't reproduce the issue with Alfred fallback search. Could you tell me what to type/search in Alfred to reproduce your problem? Thanks!

**Comment by iT-Boyer** [comment]
Through verification, it is not caused by Chinese characters. 
the problem is that if you use `obsidian://open` / `obsidian://search` to open the file, this error will appear.  so I corrected the title of the issue。
This Alfred fallback search workflow has the same problem：
![截屏2021-02-24 下午1 39 17](https://user-images.githubusercontent.com/4022953/108953162-b3040a80-76a5-11eb-9ee0-d277b799c99c.png)

**Comment by hauselin** [comment]
For me to try to fix the problem, I'll have to be able to reproduce it on my computer. Could you tell me what are the exact steps I'll need to take to reproduce the problem? Otherwise, I only know you're having problems but I have no idea how to reproduce it so I can't fix anything at all. So it'd be much more useful if you could tell me the exact steps (e.g., which command, what you typed) and what the problem/output is. Thanks!

**Comment by iT-Boyer** [comment]
1. Configure this `Search Obsidian For `command and activate it .
![](https://user-images.githubusercontent.com/4022953/108953162-b3040a80-76a5-11eb-9ee0-d277b799c99c.png)
2. enter any text in Alfred.
![截屏2021-02-25 上午9 35 10](https://user-images.githubusercontent.com/4022953/109089783-c4542200-774c-11eb-9804-ca60df96cf90.png)

**Comment by hauselin** [comment]
I can't reproduce it. It works fine on my computer. Did you happen to have modified the workflow/code while fixing the problems raised in #17? If you've changed something, I recommend you try re-installing the workflow. 

Also, what's the error message in Alfred's debug pane when you perform the two steps you described? For me, the last two lines of output are the following:

```
[22:28:39.492] STDERR: Obsidian[Run Script] Running script - fallback search
obsidian://search?vault=notes&query=keyw
```

Fallback search works fine for me.

![search](https://user-images.githubusercontent.com/7620977/109103024-ab695380-76ef-11eb-9039-a2cf317a38b1.gif)

**Comment by hauselin** [comment]
> ![截屏2021-02-22 下午2 52 29](https://user-images.githubusercontent.com/4022953/108672894-bcfb0180-751d-11eb-9c9f-b8b70ff78e1a.png)

Also, your path looks weird/wrong to me. There are two slashes `//` after your iBooks directory `iBooks`. Did you modify it manually because you were trying to get `~` to work (as in #17)? If you did, you should manually remove the extra slashes that are in environment variabes.

**Comment by iT-Boyer** [comment]
This issue is caused by the `vault` variable。
For example, set the path of the `vault1` to `~/test`, set the value of `vault8` to the subdirectory of the middle `vault1`: `~/test/ibook`, This will result in that vault8 cannot be found, and when executing the `obsidian://search?vault=vault8` Time.
