### ISSUE TITLE
Starting Obsidian from an Alfred-selected note doesn't start Obsidian with that note

### ISSUE THREAD

**Issue by slnc** [hauselin/obsidian-alfred#23]
Instead obsidian-alfred (2.6.0) opens Obsidian (0.11.3) with the last opened note. I believe we discussed this in the past, but I don't see any open issues so I'm reporting it again in case it's not intended.

I know as a workaround I could keep Obsidian open, but I prefer not doing that because if I leave apps open while I'm not using them it makes cmd-tab navigation cumbersome. Is there any way to fix this issue?

**Comment by hauselin** [comment]
I believe this problem is a [known limitation of Electron](https://forum.obsidian.md/t/mac-opening-specific-obsidian-vault-other-than-last-open-when-app-is-not-already-open-fails/7927), so I might not be able to fix it...

**Comment by slnc** [comment]
Oops, understood. I'm not familiar with AppleScript but perhaps this
solution
<https://forum.obsidian.md/t/mac-opening-specific-obsidian-vault-other-than-last-open-when-app-is-not-already-open-fails/7927/6?u=juan>
could
work for us? I guess it might require more work that you might not have
time to. Just an idea.

If it's really not possible, consider adding it to a Known problems or
Limitations section of the README.md because I think this is a pretty
common user journey if obsidian-alfred becomes more popular. It might
prevent reports like mine.

Thanks

**Comment by hauselin** [comment]
I can take a look and think about what solutions are available. It might be possible to open Obsidian first, then open the note, rather than try to do them both at the same time. I'll post an update if I find an easy fix...

**Comment by slnc** [comment]
Got it, thank you Hause. :-)

**Comment by hauselin** [comment]
Weird. For some reason, I can't reproduce this bug anymore. I closed Obsidian, used `os` to search for a note that was different from the one that was last opened, opened the note via Alfred, and Obsidian did open the correct note instead of the last-opened note. 

Could you tell me the exact steps you took to produce the bug? Thanks!

**Comment by hauselin** [comment]
I've implemented a rather simple workaround for now. Basically, the scripts always try to open the note twice. After the first try, it waits 3 seconds, then opens again. That 3 seconds wait should be long enough for Obsidian to open, and then it'll try to open the note again. But if Obsidian is already opened, the second time the script tries to open the note again, not much will happen other than Obsidian notifying you again that the note is opened (which isn't that annoying relative to notes not opening properly).

Try [this updated version](https://www.dropbox.com/s/57zljg5u3hfq22s/Obsidian_test.alfredworkflow?dl=1) and let me know if it works. It seems to work on my computer.

**Comment by slnc** [comment]
Oh, wow, thanks a lot Hause! With the new version I can't reproduce the
issue anymore, the only caveat is the double-message of "Opened note XXX"
that appears at the top. I guess there is no way of asking Obsidian which
note it has opened and to not send the second open command unless
necessary, right?

**Comment by hauselin** [comment]
Yea, no easy fix for that double-message/notification. But it's probably not too annoying anyway, relative to the note not opening properly, I guess. 

Since it's fixed, I'll release an update later today. And if you're enjoying the workflow, consider sponsoring ;)

**Comment by slnc** [comment]
Thank you, I will consider the sponsor option! 😊
