### ISSUE TITLE
Vault connecting issues

### ISSUE THREAD

**Issue by Harvison** [hauselin/obsidian-alfred#26]
Hi,

Please let me note that all is most likely fine with the Alfred workflow. It would most likely be me at fault and user ignorance or error.

Someone from the Obsidian Forum sent me here to get the workflow being as there is no way, other than Alfred to open, create, or modify files in Obsidian without opening them within Obsidian.  

I downloaded and installed the workflow, but I am having trouble connecting to my vaults.  They are in iCloud Drive.  The reason for keeping them there, I can use Obsidian on the Mac OS and Taio on iOs.  My understanding of the iCoud Drive for mobile, the files need to reside there for ease of operation in the Taio app.  All is fine with Obsidian seeing all the files and folders, as well as Taio doing the same.

The only available area for connection that I can see when assigning a vault to Alfred, is ~/iCloud.  Connecting to that, does not link anything to Obsidian.

The real area where all the folders reside is:
iCloud Drive/Taio/Editor. There are many folders and subfolders beyond the Editor subdirectory.  I included this information just incase it would be of help.

Any help would be greatly appreciated,
Thank you,
Dan

**Comment by hauselin** [comment]
I'll need more information before I can help. 

Which commands aren't working for you? Is `oo` working for you? Did you follow the setup instructions [here](https://github.com/hauselin/obsidian-alfred#set-up)? Also, check out #17, which might be relevant. It'd be helpful if you can show me what are your environment variables (see #17 and #11 if you're unsure what I'm referring to).

**Comment by Harvison** [comment]
Hi Hausellin,

I read the reference notes you listed in the reply.  I manually removed the vaults like specified in those articles. I removed the workflow and then reinstalled it, also reassigning the vault. The "oo" shortcut does open to my main vault. 

I cannot however see, or open any files within the Obsidian vault. I assigned the daily vault and it will create a new note, but only seems to do so in the root directory of the vault.

I am not able to open any notes in the vault, as they are not seen in the Alfred workflow area. 

These keywords:  os, or, ot (or oss, orr, ott) give the the search criteria, i.e. search within 3 days etc., but none of them yield any results. Doing an oss, this is the debug information:
[10:26:34.767] Logging Started...
[10:26:55.502] Obsidian[Keyword] Processing complete
[10:26:55.503] Obsidian[Keyword] Passing output '' to Run Script
[10:26:55.618] STDERR: Obsidian[Run Script] Running script
Found 2 vaults
[10:26:55.619] Obsidian[Run Script] Processing complete
[10:26:55.619] Obsidian[Run Script] Passing output '' to File Filter

Please forgive my ignorance. It is like trying to teach a dog to climb a ladder and squirt a hose at a fire, so to speak.  This is all new to me.

Thanks,
Dan

**Comment by hauselin** [comment]
The debug output looks fine to me. There aren't any obvious errors and it managed to find your two vaults. 

Could you try the solutions suggested in #15? They might fix your problems. It could be that because of where your vault is located, it thinks those files are system files. Again, there are [3 potential solutions](https://github.com/hauselin/obsidian-alfred/issues/15#issuecomment-753414360) and different solutions have worked for different people. Let me know how that goes.

**Comment by Harvison** [comment]
Reading through the last suggested thread you posted for me to look at and try, nothing worked and down the list of replies to that thread I went.  Coming to @etiennepellegrini post, I tried that and now os works.

I have yet to try the other things that were not working.

**Comment by Harvison** [comment]
Since the last post, finding and opening files works fine. Appending an inbox note does not and now the daily note does not work. 

Thx Dan

**Comment by hauselin** [comment]
> Since the last post, finding and opening files works fine. Appending an inbox note does not and now the daily note does not work.
> 
> Thx Dan

My hunch is that the paths to your inbox and daily notes haven't been specified correctly. For the daily note, you'll have to make sure a few other settings are correct (see [here](https://github.com/hauselin/obsidian-alfred#set-up) again).

It'd be helpful if you show me the debugging output when you run `od` and `oi`, just like what you did [previously](https://github.com/hauselin/obsidian-alfred/issues/26#issuecomment-802871267).

**Comment by Harvison** [comment]
Thank you for your patience.

I have gotten a lot accomplished since the last reply.  I am now able to open any and all MD files in Obsidian, create a new daily note, today, tomorrow, etc. I am also able to add things to the already existing inbox note.

I think I actually got all working now.

Thanks for all your help.

**Comment by hauselin** [comment]
Awesome. Glad it's working for you now.
