### ISSUE TITLE
Automatically add a time stamp at the end of an item when using oi

### ISSUE THREAD

**Issue by wenlzhang** [hauselin/obsidian-alfred#27]
Is it possible to add a time stamp when adding items to the selected inbox note? This way, one may easily check when an item is added to the inbox. For instance, the item may look like the following: "This is an item to be added to the inbox 202103281502".

Further, it may also be interesting to be able to customize the suffix. For instance, the current date "2021-03-28" or the link to the current daily note "[[2021-03-28]]" may be the desired suffix for some users.

In case some users may not like this kind of suffix, one may choose whether to append such a suffix to the inbox note.

**Comment by hauselin** [comment]
Try [this updated workflow](https://www.dropbox.com/s/oavm10kepeij71n/Obsidian.alfredworkflow?dl=1). Use `oinboxtime` to configure first. Let me know if it works for you. 

If you want to change the format of the timestamp, modify it here:

![image](https://user-images.githubusercontent.com/7620977/112761884-90be1f00-8fba-11eb-8485-ec2c18c73784.png)

**Comment by wenlzhang** [comment]
Great! It works perfectly for me.
