### ISSUE TITLE
Use "List Filter" for vault selection

### ISSUE THREAD

**Issue by hjklapp** [hauselin/obsidian-alfred#3]
Thank you for this helpful workflow!
If you use a list filter for the selection of the fault, the vault names appear as Alfred items. This allows for the auto completion or vault names and makes the vault names also selectable/actionable.

If you want, I can provide the modified workflow.

**Comment by hauselin** [comment]
Thanks for the suggestion, @hjklapp! That's a great idea. I'll include it in my next update and will acknowledge your contribution!
