### ISSUE TITLE
A little setup feedback and one small request

### ISSUE THREAD

**Issue by patowod** [hauselin/obsidian-alfred#30]
Hi, this is a really great workflow. I've had a few issues while setting up and thought I'd share my solutions for others and as feedback. 

- I use iCloud drive as location for my vault. oaddvault didn't find my vault until I made sure that the path was also added to Alfreds default search location.
- The listed examples under odailyformat didn't catch my edge case, as I use "2021-05-14-Fri" which would translate to "yyyy-mm-dd-ddd" I noticed somewhere that many people aren't aware that they can change these values in the upper right through the [x] icon.
- odailytemplate: I use a folder in my vault named templates. While I was able to navigate and select the correct template file this selection was not written into the variable. Workaround: just select a note in your root vault and edit / add subfolder and template name with extension ".md" in the variable "dailytempabspath" (under upper right [x] when workflow is selected)

Those where my steps to make all the bells and whistles chime. One question though: would it be possible to make the current daily note act as inbox note?

Thanks for this workflow. It's exactly what I was looking for and after initial setup it works beautifully!

Have a nice day everyone. Cheers 🙌

**Comment by hauselin** [comment]
Thanks for the detailed documentation and suggestions! If you feel like it, feel free to fork the repository, make changes to the README, and make a pull request. If not, I'll update the documentation/README in the next week or so. 

> One question though: would it be possible to make the current daily note act as inbox note?

Yes, `oi` will append text as a list item/bullet point to the end of any file.

**Comment by leadangle** [comment]
How can we get rid of the default alfred dynamic placeholders?
