### ISSUE TITLE
RFE request to add quick journal entry to DailyNotes

### ISSUE THREAD

**Issue by anishvash** [hauselin/obsidian-alfred#31]
Awesome work!
This is the only Alfred workflow which has worked for me.

One RFE request, similar to adding quick note/journal entry to an inbox file, it will be great if one can add quick journal entry to the Daily note . 

Thanks.

**Comment by hauselin** [comment]
You can now use `odi` to append text to your daily note. Make sure to use `od` at the start of the day (updated readme).

**Comment by anishvash** [comment]
Thank you for the quick resolution!
