### ISSUE TITLE
Umlauts in the file path of the note are not encoded

### ISSUE THREAD

**Issue by hjklapp** [hauselin/obsidian-alfred#4]
Hi, umlauts and other special characters in the file path of the note are not encoded when constructing the url scheme.

One way to fix this is to replace the bash actions/scripts by JXA actions/scripts. Here is the code of the search script (given input by `os`, `or`, `ot`):

```js
// absolute file path to file
p="{query}"

// construct obsidian url scheme (0.9.0); see https://forum.obsidian.md/t/obsidian-release-v0-9-0-insider-build/5975
url = "obsidian://open?path=" + encodeURIComponent(p)

// get the current app to access the standard additions
app = Application.currentApplication();
app.includeStandardAdditions = true;

// open file in vault
app.openLocation(url);
```

**Comment by hauselin** [comment]
Thanks again, @hjklapp! I've updated the workflow to use JXA actions/scripts.

**Comment by hjklapp** [comment]
I'm glad to contribute, your workflow is very useful for me!
