### ISSUE TITLE
Is there currently any way to search for attachments inside vaults (e.g. png, pdf files) ?

### ISSUE THREAD

**Issue by champagnealexandre** [hauselin/obsidian-alfred#41]
Setting up obsidian — along with this awesome plugin — and just found out that obsidian supports viewing e.g. PDF files directly in their own interface, i.e. without having to embed them in a markdown file or anything.

So instead of adding a bunch of .md files that embed PDFs I’ll simply add those to the vault ; they’re shown in the file explorer along with .md files. However I can’t seem to find them through obsidian-alfred’s search feature. Is this implemented somehow?

Thanks for the great plugin btw!

**Comment by hauselin** [comment]
By default, this workflow (`os`, `or` etc.) only returns markdown files. But it's easy to search for attachments/other file types. See instructions/video below:

https://user-images.githubusercontent.com/7620977/133846513-999754a2-916c-41f2-98b8-0c80fdd1932c.mp4

![Screenshot_20210917_135743](https://user-images.githubusercontent.com/7620977/133846524-906e7953-462a-46c4-84e4-c2c558bc8ef5.png)

**Comment by champagnealexandre** [comment]
Really cool, works like a charm. Thank you!
