### ISSUE TITLE
Search (os, oss, or, orr) does not work.

### ISSUE THREAD

**Issue by szfkamil** [hauselin/obsidian-alfred#55]
I know this is the same issue as issue #15, but none of the solutions worked for me. I am using `Alfred 5.05.`

**Comment by szfkamil** [comment]
I'm not sure what information to provide, just let me know what you need to look into this!

**Comment by thingnotok** [comment]
Have you upgraded to Ventura? I have the same issue. Alfred' s file filter can not find files when scope is provided.

**Comment by szfkamil** [comment]
> 

Yes! That might be the issue. I will have to stop upgrading the OS shortly after the release. People are right; give it a few months.

**Comment by szfkamil** [comment]
@thingnotok Hey. Can you help?

**Comment by thingnotok** [comment]
Hey, sorry I forgot this one. I resolved this by avoiding "provide search scope". There's a [detailed explain](https://www.alfredforum.com/topic/17774-alfred-cant-find-folders-and-files-but-spotlight-can/) on how to do this explicitly.

But maybe they have fixed that bug in recent releases, maybe you can try to upgrade alfred first.

**Comment by szfkamil** [comment]
I am on 5.0.6 latest ver. `os`, and `oss` still do not work. I followed the guide and still need help. I can search the files through Alfred but not through the command.

**Comment by szfkamil** [comment]
`od` works
`otmrw` works
but `odi` does not? 
`os` only displays .txt files. it searches .txt instead of .md it seems
`oss` nothing at all
`on` works
all inbox commands work too

it's just the damn search scope which does not haha

**Comment by szfkamil** [comment]
Tbh. It's most likely the fault of my system, not the plugin. After migrating devices, I have had search problems for a long while, but it's too technical for me to fix. The solutions from Alfred didn't work for me, or they did only temporarily. I might have a better look at them again since I really want this to work for me.
