### ISSUE TITLE
od fails if you haven't created a note yet

### ISSUE THREAD

**Issue by technicalpickles** [hauselin/obsidian-alfred#6]
I haven't started a Daily Note yet, and I get this when running `od`:

![image](https://user-images.githubusercontent.com/159/98013455-6334c700-1dc8-11eb-8d49-65aa28c633a1.png)

It works as soon as I click "Open today's note" the first time.

**Comment by hauselin** [comment]
This problem isn't easy to fix, at least for now, since [Obsidian's URI](https://publish.obsidian.md/help/Advanced+topics/Using+obsidian+URI) doesn't support creating daily notes (or any note) yet. I can certainly create a new empty file with the specified date format, but it's probably not a great solution.

I'll leave this issue open until there's a good solution. But in the meantime, I'll remind users to create the daily note in Obsidian first. Thanks!

**Comment by luckman212** [comment]
@hauselin One solution (this is what I do) is to store your daily note template in a specific location, and then within your script, test if the daily note exists. If it does _not_, then copy the template into the daily note location (with formatted date string) first, and then open Obsidian with the URL scheme. This works for me (but I agree it's hacky and would be better handled if Obsidian natively supported the today action...)

**Comment by hauselin** [comment]
Yea, @luckman212, I have similar ideas in mind and agree they're a bit hacky. Users will have to also specify whether their daily notes are in a particular directory (e.g., I keep my daily notes in a daily directory inside my vault) and where their daily-note template is located (assuming they use templates). 

I'll think about it more and I hope Obsidian will let us create notes in the near future.

**Comment by hauselin** [comment]
@luckman212 and @technicalpickles, if you want, try this osascript to see if it works... Added step 3 (optional step). If you do try it, let me know if you catch any bugs. It's not yet incorporated into the workflow.

```
// This action only opens existing notes. It won't create a new daily note that doesn't exist yet—you'll get a file not found message instead; if so, create the daily note in Obsidian first.

// step 1: specify daily note date format (e.g., 1st March 1990)
// example 1: "yyyy-m-d"  if your date format looks like 1990-3-1
// example 2: "yymmdd"    if your date format looks like 900301
// example 3: "d_m_yy"   if your date format looks like 1_3_90

// indicate your date format below by replacing "yyyy-mm-dd" with your format
date_format = "yyyy-mm-dd"; 

// step 2: specify vault name
v = "notes";

// all STEPS below are optional

// step 3 (OPTIONAL): follow this step if you want Alfred to create a new daily note that doesn't yet exist
// specify the absolute/full path to the directory where you keep your daily notes
fulldir_daily = ""
// if you have a template for your daily note, specify the absolute/full path to this note
fullpath_template = ""




// don't need to edit the lines from here onwards
date_format = date_format.toLowerCase();

// determine no. of y, m, d needed
n_y = date_format.split('y').length - 1;
n_m = date_format.split('m').length - 1;
n_d = date_format.split('d').length - 1;
y_char = "y".repeat(n_y);
m_char = "m".repeat(n_m);
d_char = "d".repeat(n_d);

// get today's date
today = new Date();
yyyy = today.getFullYear().toString();
mm = (today.getMonth() + 1).toString();
dd = today.getDate().toString();

// format date according to user specification (e.g., yy, m, d)
yyyy = yyyy.slice(4-n_y, 4);
if (mm.length == 1) {mm = mm.padStart(2, '0').slice(2-n_m, 2)};
if (dd.length == 1) {dd = dd.padStart(2, '0').slice(2-n_d, 2)};

date_format = date_format.replace(y_char, yyyy);
date_format = date_format.replace(m_char, mm);
date_format = date_format.replace(d_char, dd);

p = encodeURIComponent(v) + "&file=" + date_format + ".md";
uri = "obsidian://open?vault=" + p;

// get the current app to access the standard additions
app = Application.currentApplication();
app.includeStandardAdditions = true;

// create new daily note if it doesn't exist
if (fulldir_daily != "") {
	// format file path
	if (fulldir_daily[(fulldir_daily.length-1)] != "/") {fulldir_daily += "/"}
	filepath = fulldir_daily + date_format + ".md"

	// get template content
	var template_txt = ""
	if (fullpath_template != "") {
		template_txt = app.read(Path(fullpath_template))
	}

	// create note with template (if exists)
	var path = Path(filepath)
	var finderApp = Application("Finder")
	if (!finderApp.exists(path)) {
		console.log("Note doesn't exist. Creating note.")
		var openedFile = app.openForAccess(Path(filepath), {writePermission: true})
		app.write(template_txt, { to: openedFile, startingAt: app.getEof(openedFile) })
		app.closeAccess(openedFile)
		uri = "obsidian://open?path=" + encodeURIComponent(filepath)
                // wait a bit for note to show up in file system
		delay(1)
	}
} 

// open file in vault
app.openLocation(uri);
console.log(uri);
```

**Comment by technicalpickles** [comment]
> if you want, try this osascript to see if it works

Thanks! I'll try it out tomorrow.

> I'll think about it more and I hope Obsidian will let us create notes in the near future.

There is a community forum with Feature Request, so it'd be worth posting there 😁  https://forum.obsidian.md/

**Comment by hauselin** [comment]
Thanks! Let me know if it works or not. I've tweaked it a bit, so make sure to use the latest version. Basically added `delay(1)` to ensure the new note has time to show up in finder before opening it in Obsidian.

> There is a community forum with Feature Request, so it'd be worth posting there 😁 https://forum.obsidian.md/

I have a feeling Lishid (the developer) might want to leave this feature for future plugins (now that they're alpha-testing their API). I've asked him about adding URI actions to open workspaces and it seems likely he'll leave it to plugin developers. But perhaps the solution provided above works well enough...

**Comment by technicalpickles** [comment]
Just tested it, and it works 🎉  Thanks!

**Comment by hauselin** [comment]
Thanks! Will incorporate it in the next release!
