### ISSUE TITLE
Add fallback search

### ISSUE THREAD

**Issue by technicalpickles** [hauselin/obsidian-alfred#7]
Alfred supports a concept of a "fallback search", if you type something in, you can try selecting a fallback method for searching like on Google, or whatever. It'd be cool to have that for obsidian too.

Here's the alfred docs: https://www.alfredapp.com/help/workflows/triggers/fallback-search/

A URI handler for search was added in 0.9.7: https://forum.obsidian.md/t/add-search-as-an-uri-action/6063/5

I was able to get this working locally with:

![image](https://user-images.githubusercontent.com/159/98615941-be375400-22c9-11eb-9abe-4ab52b8e9d67.png)

I copied one of the existing osascripts, and updated it to:

```
// step 1: specify vault name
v = "your-vault";

// search query
p="{query}";

// construct uri
uri = "obsidian://search?vault=" + v + "&query=" + encodeURIComponent(p);

// get the current app to access the standard additions
app = Application.currentApplication();
app.includeStandardAdditions = true;

// search in vault
app.openLocation(uri);
console.log(uri);
```

**Comment by hauselin** [comment]
This feature is actually very similar to searching with Alfred's file filters, which are used by the `os`, `ot`, and `or` keywords. I can try to add Obsidian's search URI to these three file filters, though I wonder it's actually that useful, since Alfred's file filters are already quite powerful. I guess the main benefit of the search URI is that it opens up the search (and results) pane in Obsidian.  

To address the fallback suggestion, I could call Obsidian's search URI only if no matching files are found with the `os`, `ot`, and `or` keywords. Then again, it'll just open the search pane in Obsidian that says no matches found. How useful would that be? 

Let me think about it more. Thoughts/suggestions welcomed!

**Comment by technicalpickles** [comment]
> This feature is actually very similar to searching with Alfred's file filters, which are used by the os, ot, and or keywords. I can try to add Obsidian's search URI to these three file filters, though I wonder it's actually that useful, since Alfred's file filters are already quite powerful. I guess the main benefit of the search URI is that it opens up the search (and results) pane in Obsidian.

Keep in mind fallback happens when you are typing into Alfred, and it's not intended to list out potential results. The other fallback searches I have search on google or in devonthink. That would include if `os` and friends fail to find anything. It wouldn't be overly

The way I'm trying to use this is to have a quick way to searching google, obsidian, devonthink without having to figure out which one I want to do when I start typing. I'd use `os` if I was trying to find something I knew was in obsidian.

**Comment by hauselin** [comment]
If possible, could you make a gif of your use case? I can't say I'm 100% sure of the intended use case or how you're using it or planning to use it (based on the code you provided above). Thanks!

**Comment by technicalpickles** [comment]
![Screen Recording 2020-11-18 at 10 19 45 AM](https://user-images.githubusercontent.com/159/99550323-9cecfc80-2988-11eb-9c18-22f8e2323022.gif)

**Comment by hauselin** [comment]
Got it! Do you want to check out the implementation in [this branch](https://github.com/hauselin/obsidian-alfred/tree/fallback-search) and let me know if you like it? It also asks you to indicate which vault to search in before performing the search. Let me know what you think.

**Comment by hauselin** [comment]
I've released a new version and will close this issue. Thanks!
