### ISSUE TITLE
Make it easier to upgrade by not having manual changes for your setup

### ISSUE THREAD

**Issue by technicalpickles** [hauselin/obsidian-alfred#8]
Several of the filters have manual steps you need to do to make the workflow work for your particular vault setup. If you upgrade it (ie download the workflow and install it), you'd lose these changes.

Ideally, the workflow provides a way to configure itself 😅  [TimeZones-Alfred](https://github.com/jaroslawhartman/TimeZones-Alfred) is one I use that does this. I haven't looked into it to see how complicated its implementation is though.

**Comment by technicalpickles** [comment]
Another option: https://www.alfredapp.com/help/workflows/advanced/variables/

**Comment by hauselin** [comment]
Haha. You're always a step ahead of me! I was actually considering using environment variables in a future release. That's relatively easy to implement (likely in the next release). And yea, I might consider implementing a configure option too, but probably not too soon. 

I've actually included an Alfred bundle id in the latest release (v0.1.5), which should help migrate some (but not all) of the settings each time you update.

**Comment by hauselin** [comment]
@technicalpickles, if you want to try it, check out the latest version I'm testing in [this branch](https://github.com/hauselin/obsidian-alfred/tree/scriptfilter) and download [the latest workflow here](https://github.com/hauselin/obsidian-alfred/raw/scriptfilter/Obsidian.alfredworkflow). If should now save all your settings and will migrate them whenever you upgrade. It requires a one-time set-up to store the relevant variables. See the README in the branch for instructions on how to set it up. 

Let me know how it goes if you try it. Thanks!
