### ISSUE TITLE
Since the last update I have to go through 2 Alfred search results and press Enter twice to open a note

### ISSUE THREAD

**Issue by slnc** [hauselin/obsidian-alfred#9]
Since the last update I have to go through 2 Alfred search results and press Enter twice to open a note.

See [Screen Recording 2020-12-07 at 10.19.05.mov.zip](https://github.com/hauselin/obsidian-alfred/files/5651710/Screen.Recording.2020-12-07.at.10.19.05.mov.zip).

Is there any way to make the search results appear directly after typing "os <some search query>" so that you can open notes with fewer keystrokes and just 1 alfred search results pane?

Thanks

**Comment by hauselin** [comment]
I'm not sure if I can fix that easily without requiring users to manually tweak that part of the workflow (I introduced environment variables in the last update to remove the need for users to do that). I'll look into it and will ask on the Alfred forums to see if it's possible. The "problem" here is that I first have to tell Alfred where to search for files (i.e., narrow its search scope via a script) so it lists only files within your vaults. This narrowing of search scope requires an extra step.

But if you don't mind the workflow also listing Markdown files that are not inside your vault, we can remove that extra keystroke. Try [this version](https://www.dropbox.com/s/gal6atk046h3vjt/Obsidian.alfredworkflow?dl=1) and let me know if you like it? The original keywords `os`, `or`, and `ot` are now `oss`, `orr`, and `ott`—they will only list files inside your vaults. The updated `os`, `or`, and `ot` will now work with just 1 keystroke, but will list all markdown files on on your computer. (This updated version also includes a new `otmr` action to create/open tomorrow's daily note, which you can ignore if you don't need the feature).

If for some reason, they don't work for you, see the screenshot below for the changes. 
![tempfix](https://user-images.githubusercontent.com/7620977/101376764-03c24f00-387f-11eb-9fca-bb19dd011723.png)

**Comment by slnc** [comment]
Thanks Hause, it works better for me!

There is something funny going on with the searches, though, but I'm not
sure how to explain it. See the attached video which shows what happens
when I type: "os[tab]start typing a note's partial title[tab][enter]". Then
at 00:07 I do almost the same thing except that I don't type the first
[tab]. When I do that, Alfred shows me my desired note first ("O- 2020 -
GROW - USGlobalInvestors") and I can immediately open it. It seems that if
I type a full word present in a note's title along with the 2 tabs,
sometimes it also work as expected "os[tab]GROW[tab][enter]", but not for
some notes, e.g. "os[tab]graftech[tab][enter]" won't leave a note that has
"something Graftech.md" in its title.

If this description is unclear, please let me know. But if you don't have
more time for this, the new version does really work better for me, this
last comment is an attempt to make the plugin work in a more predictable
fashion with fewer keystrokes, that's all. :-)

Thanks!

**Comment by hauselin** [comment]
Great. I might update the github version too if that's preferred. 

Can you attach your video again? It doesn't look like it's been uploaded. Thanks!

**Comment by slnc** [comment]
Thanks Hause.

Here is the video, now uploaded via Github instead of reply-by-email: 

[Screen Recording 2020-12-08 at 17.37.59.mov.zip](https://github.com/hauselin/obsidian-alfred/files/5660911/Screen.Recording.2020-12-08.at.17.37.59.mov.zip)

**Comment by hauselin** [comment]
Hm... I'm not 100% what the problem is, though I did find a "bug." Try checking the box below if it isn't already checked. Click on the `os` File Filter action to open up that pane. Let me know if it solves your problems. If not, try removing the `oss`, `orr`, and `ott` keywords. They might be interferring with things too...

![bug](https://user-images.githubusercontent.com/7620977/101523496-aef20780-3956-11eb-8765-eb9817ea670c.png)

**Comment by slnc** [comment]
Oh, yeah, that seems to have fixed it. Thanks! :)
